### ISSUE TITLE
Use TGPuttyLib in C++ Builder XE

### ISSUE THREAD

**Issue by engi** [superflexible/TGPuttyLib#1]
Is it possible to use TGPuttyLib SFTP Client in C++ Builder XE ?

**Comment by superflexible** [comment]
It is surely possible but I haven't tested it. Maybe some modifications need to be done. I will eventually make native C++ bindings too. I will post more info as soon as I have them.

**Comment by superflexible** [comment]
Hello,
I am working on a C++ library now. The Delphi one can't be used directly.

**Comment by engi** [comment]
Thanks in advance !!!

**Comment by superflexible** [comment]
Hello,
you will now find C++ bindings in the files tgputtylib.cpp and tgputtylib.hpp.

There's a small demo in CPPDemos/Simple.

So far the C++ bindings are only basic DLL imports, not classes or even a component like the Delphi files. But as you can see in the demo, you can absolutely work with this.

A C++ class and a native C++Builder component will be added later.

**Comment by superflexible** [comment]
I have now added a C++ Builder class in tgputtylibcbclass.h and tgputtylibcbclass.cpp, as well as a demo in CPPDemos/CPPBuilderClassDemo.

Note that this is a class, not a component. See the demo on how to use it.

**Comment by engi** [comment]
I'll have a look on it next monday. Thanks

**Comment by superflexible** [comment]
Hello,
I have now added a C++ Builder Component and a fully working VCL GUI SFTP Client App made with C++ Builder (no Delphi parts). But this is for the latest XE 10.3.3. It may take some extra steps to install this into older C++ Builder versions.

It's probably best to not try to install the component, and instead create the class and assign all properties in code. For example,

TTGPuttyCBSFTPClient *myClient = new TTGPuttyCBSFTPClient(NULL);

myClient->HostName = L"192.168.12.12";

etc.

**Comment by superflexible** [comment]
I have tested it with C++ Builder XE6 now. You can just add the cpp files to your project and create the component in code, or create a new C++ Component Package and add these files:
ctgputtylib.cpp, tgputtycbsftpclient.cpp, tgputtylibcbclass.cpp

They need to be added to the project too.

**Comment by engi** [comment]
Hello,
I used the class with some modifications and everything works perfectly under Builder XE.
Thank you very much for the work done!

**Comment by superflexible** [comment]
Hello,
many thanks, that's truly good news. I will close this ticket now but feel free to contact me if there are any other issues or requests.

**Comment by alexchip64** [comment]
Sorry Engi, could you please indicate which modifications have you done? I am asking because I am having some problems with the declaration of the events (I think I have to modify all of them in order to have a "void" result, not a "bool"). The properties/members work well though, I have only this problem with the events.

**Comment by engi** [comment]
Hi Alexchip64,
I'm using TGPuttyLib v 0.73, but only the class (not the component) and everything works fine.
Here is my implementation :
`
SFTPClient = new TTGPuttyCBSFTPClient(NULL);
SFTPClient->OnSFTPChangeState = TGPuttySFTPClientSFTPChangeState;
SFTPClient->OnSFTPMessage = TGPuttySFTPClientSFTPMessage;
SFTPClient->OnSFTPListing = TGPuttySFTPClientSFTPListing;
SFTPClient->OnSFTPVerifyHostKey = TGPuttySFTPClientSFTPVerifyHostKey;

SFTPClient->HostName = thSFTPAdresse;
SFTPClient->Port = thSFTPPort;
SFTPClient->UserName = thSFTPUserId;
SFTPClient->Password = thSFTPUserPwd;
`
and event example :
`
bool __fastcall TForm1::TGPuttySFTPClientSFTPVerifyHostKey(TObject* Sender, const UnicodeString host, const int port, const UnicodeString fingerprint, const int verificationstatus, bool &storehostkey)
{
	storehostkey = true;
	return true;
}
`

I'm not using returned value but everything is ok
