### ISSUE TITLE
Why some Events return a boolean?

### ISSUE THREAD

**Issue by alexchip64** [superflexible/TGPuttyLib#10]
I am converting the lib, in order to be used in a C++ XE compiler (don't ask me why; it is complicated!). 

However, I don't understand why some of the events created (OnSFTPProgress, etc.)  have a return value. This is generating some problems using this compiler in the program that uses this package.

For example, in the library there is this declaration: 

`typedef bool (__closure *TOnProgress)(const __int64 bytescopied, const bool isupload);`

In the XE program that uses this library, the event is created in this way:

`Pointer  __fastcall `TFMain::TGPuttySFTPClient1SFTPProgress(TObject` *Sender, TSFTPProgressInfo * const ProgressInfo)`

While in a XE8 compiler, the event generated is:

`bool __fastcall TFMain::TGPuttySFTPClient1SFTPProgress(TObject *Sender, TSFTPProgressInfo const * ProgressInfo)`

But, anyway, it is an event! How can I suppose to read the result value?

May I change the library, so all the events will return a "void" result? Or there is anything that I have missed?

**Comment by superflexible** [comment]
Hello,
if this event returns false, the transfer will be aborted. So this is an additional way of canceling a transfer gracefully.

If you can't return a bool correctly, you need to modify the function TTGPuttyCBSFTPClient::DoProgress in tgputtycbsftpclient.cpp.

Instead of the line
return FOnSFTPProgress(this,ProgressInfo);
you would need:
FOnSFTPProgress(this,ProgressInfo);
return true;

**Comment by alexchip64** [comment]
Thank you. I have modified all the "Doxxxxx" routines accordingly, adding a "result" reference parameter where needed, in order to return the response.

For example:

`typedef void __fastcall (__closure *TOnSFTPGetInput)(System::TObject* Sender, System::UnicodeString &AnInput, bool &result);`

and in the "DoGetInput" I've changed in this way:

`bool TTGPuttyCBSFTPClient::DoGetInput(char* linebuf, const int maxchars) {`
`    if (FOnSFTPGetInput) {`
        `UnicodeString input;`
        ` bool result=true;`
        ` FOnSFTPGetInput(this,input,result);`
        ` AnsiString line=UTF8Encode(input);`
        ` if (!result) return false;`
        `// ... omissis ....`
`}`
