### ISSUE TITLE
First impression - well done!

### ISSUE THREAD

**Issue by edwinyzh** [superflexible/TGPuttyLib#12]
So I started evaluating and choosing a sFTP client.

I'm testing it against a FreeSSHd SFTP server on local Windows, and an OpenSSH server also on Windows.

- I first tried https://github.com/pult/libssh2_delphi, it can connect to OpenSSH, and failed to connect to FreeSSHd (returns some thing like 'waiting for password response' which I couldn't figure out how to fix).

- Then I tried SecureBridge (not the latest version, I don't have it. It's an old version released about 2 years ago). It failed to connect to the local FreeSSHd server (I foroget the error message), so I stopped testing it further.

- At last I tested TGputtyLib, and **it can connect to both of the servers**! I'm testing it further now...

**Comment by superflexible** [comment]
Many thanks! Of course in this case, we have to thank the PuTTY developers, I only made the DLL version.

**Comment by edwinyzh** [comment]
@superflexible , you are right, I should thank you and the PuTTY developers for sharing the great works!

Out of curiosity, what does the 'TG' prefix mean?

**Comment by superflexible** [comment]
My name - Tobias Giesen :=)

**Comment by edwinyzh** [comment]
I see now!
