### ISSUE TITLE
Where to find the meanings of the error codes?

### ISSUE THREAD

**Issue by edwinyzh** [superflexible/TGPuttyLib#13]
Hello Tobias,

When I get errors like:
> TGPuttySFTPException: tgsftp_cd: Error 5, bad message

Where I can find a list of such errors along with the explanations of the errors?

PS, from the log of the FreeSSHd the error is that the directory the client want to change to doesn't exist.

Thanks!

**Comment by superflexible** [comment]
Hello,
these are standard SFTP error codes. "Bad message" is the complete error message. You can use the following Google Search: 
"Bad message" sftp

There aren't many SFTP error codes. They are defined in sftp.h:
#define SSH_FX_OK                                 0
#define SSH_FX_EOF                                1
#define SSH_FX_NO_SUCH_FILE                       2
#define SSH_FX_PERMISSION_DENIED                  3
#define SSH_FX_FAILURE                            4
#define SSH_FX_BAD_MESSAGE                        5
#define SSH_FX_NO_CONNECTION                      6
#define SSH_FX_CONNECTION_LOST                    7
#define SSH_FX_OP_UNSUPPORTED                     8

**Comment by superflexible** [comment]
More info: the error code comes directly from the SFTP server. So you need to ask FreeSSHd support in which situation the error code 5 can occur. I doubt that you can get much more information on it. This is more like something each developer needs to find out for herself or himself.

**Comment by edwinyzh** [comment]
Very helpful! Thank you Tobias
