### ISSUE TITLE
VCL demo code runs, component and my code blow up

### ISSUE THREAD

**Issue by thetoolwiz** [superflexible/TGPuttyLib#16]
I'm running D10.2 and copied the file tree to a folder, built the libs and component and installed the component.

I tried to open the VCL component demo and it gave a weird "External Exception C06D007E" while opening the form, and didn't load the component properly.

So I opened the VCL non-component demo and it builds and runs just fine.

I copied the code to init everything from this running app into my app. It compiles fine, but it blows up when it get to initializing the DLL. Same error as the component (different address).

I don't work with DLLs very much, and this just seems to be throwing an unhandled exception. I'm not sure what to do to make it work, or why the one demo would work fine and my code that's doing the exact same stuff would blow up.

Is there supposed to be a delay in opening the DLL so it can get the OnVerifyHostKey callback configured? Because it's blowing up on the initial Create with no opportunity to set the callback.

It's blowing up here:

```
constructor TTGPuttySFTP.Create(const verbose:Boolean);
var puttyversion:Double;
    tgputtylibbuild:Integer;
begin
  tgputtygetversions(@puttyversion,@tgputtylibbuild);    <<-----------------
```

**Comment by pult** [comment]
This usually happens when the x86 and x64 DLLs are confused. Best practice rename x64 to *x64.dll

**Comment by superflexible** [comment]
Hello,
the initial Create constructor does not use any callbacks.

I think you did not copy the DLL into the output folder where your EXE is compiled to.

**Comment by thetoolwiz** [comment]
looks like that solved the problem. The DLL *IS* in the search path, tho. Very strange. Thanks!

**Comment by maesGitHub** [comment]
I copied the dll to the BPL directory where the TGPuttyLib.bpl is located.  The problem only occurred with the visual component (TGPuttySFTPClient ) not with the TTGPuttySFTP.  

It works now, thanks.
