### ISSUE TITLE
How to use OpenFile?

### ISSUE THREAD

**Issue by x200516** [superflexible/TGPuttyLib#20]
Can you provide an example of calling openFile? Thanks.

**Comment by superflexible** [comment]
Hello,
this function works in conjunction with the xfer_* functions.

There's an example in the function TTGPuttySFTP.DownloadStreamP in the file tgputtysftp.pas.

It uses tgputty_openfile which is equivalent to TTGPuttySFTP.OpenFile.

Uploading is similar although the precise use of the xfer_* functions in uploads is different. Let me know if you need an example for that.

**Comment by x200516** [comment]
In fact, I want to get the size of the server file after the file is uploaded,But in ListingCallBack "names.names[i].attrs.size" is always 0.
Can you tell me how to get the filesize in server? The example is also display size 0 in stringgrid.


Thanks.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "superflexible/TGPuttyLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [superflexible/TGPuttyLib] How to use OpenFile? (#20)





 
Hello,
 this function works in conjunction with the xfer_* functions.
 
There's an example in the function TTGPuttySFTP.DownloadStreamP in the file tgputtysftp.pas.
 
It uses tgputty_openfile which is equivalent to TTGPuttySFTP.OpenFile.
 
Uploading is similar although the precise use of the xfer_* functions in uploads is different. Let me know if you need an example for that.

**Comment by x200516** [comment]
Thank you for your reply. It may be a problem with the server settings.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "superflexible/TGPuttyLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [superflexible/TGPuttyLib] How to use OpenFile? (#20)





 
Hello,
 I use the GetStat function and it usually works fine. Maybe with some servers you have to wait and repeat the function call until you get the info.
 
var Attrs:fxp_attrs;
 
PSFTPClient.GetStat(FileName),Attrs);

**Comment by superflexible** [comment]
Some SFTP servers might be "hardened" and not allow even some basic SFTP functionalities. For example, you might be allowed to upload only and not get a listing or file properties.

Another frequent problem with verifying a file size after upload is that the server processes and removes the file, so it's already gone when you try to verify the size.
