### ISSUE TITLE
GetTickCount64 : E2003 Undeclared identifier

### ISSUE THREAD

**Issue by ArchStenton14** [superflexible/TGPuttyLib#21]
Hi,

Can't use TTGPuttySFTP class with my Delphi 10.1 Berlin on win 10 : GetTickCount64 not found.
GetTickCount is in Winapi.windows.pas, but where is GetTickCount64 ?

**Comment by superflexible** [comment]
Hello,
if it's missing, you can add it to TTGPuttySFTP.pas like this:
function GetTickCount64: UInt64; stdcall; external kernel32 name 'GetTickCount64' delayed;

**Comment by ArchStenton14** [comment]
Hi Tobias, it works great
Thank you very much for you help
Best regards
