### ISSUE TITLE
puttylib.dll version 0.76?

### ISSUE THREAD

**Issue by rosch100** [superflexible/TGPuttyLib#22]
I cannot seem to find a compiled dll version 0.76.
How can I compile it myself?

**Comment by superflexible** [comment]
Hello,
I have updated the DLL now:
https://github.com/superflexible/TGPuttyLib/tree/master/Win64/Debug

To compile yourself, you need Visual C++ (I use Visual Studio 2019, the free edition). Open "x64 Native Tools Command Prompt for VS 2019". CD into the windows subfolder of your TGPuttyLib sources. Then run
`nmake -f Makefile64.vc tgputtylib.dll`
