### ISSUE TITLE
How to get file list with separate attributes?

### ISSUE THREAD

**Issue by patlecat** [superflexible/TGPuttyLib#25]
How to get a list of files in a directory with their names, timestamps, filesizes etc as individual fields? Doing the "ls" outputs to the console the list but I can't access the string of the output nor do I see how I can get a list of files like in a <vector> to access them? I'm using C++ (with GCC under Linux and VisualStudio under Windows) and saw that these class-files are different per compiler vendor but both incomplete with regards to the C interface:

- tgputtylibcbclass
- tgputtylibvcclass

**Comment by patlecat** [comment]
Ok but I can't see an example usage of a callback function and I did not find any hints in code or doc to see how this is used.

What I use now:

```
// List dir
std::cout << "**** LS ****" << std::endl;
res = tgsftp_ls("/TestFolder", &Ctx);
```

How would I apply a callback function here and what would I get, a string or a structure? If structure then which and what are it's members?

**Comment by patlecat** [comment]
This gives me the amount of entries, but how to iterate through them?
`uint64_t asize = names->names->attrs.size;`

**Comment by superflexible** [comment]
Yes, totally normal.

**Comment by superflexible** [comment]
Those are standard Unix fields, please Google Unix stat. For example 
https://man7.org/linux/man-pages/man2/stat.2.html

I will post some details here too.

**Comment by superflexible** [comment]
To detect a directory, you can do:
if ((names->names[idx].attrs.permissions & 0xF000) == 0x4000)
{
}

The time are standard Unix times (I believe seconds since 1 Jan 1970). Conversion functions depend on the compiler and libraries that you use.

mtime is the modification time. The other times are mostly useless.
