### ISSUE TITLE
Error running FPCSFTPClassTest on Raspberry Pi FreePascal

### ISSUE THREAD

**Issue by Oli1L** [superflexible/TGPuttyLib#29]
Hello guys.
Program compiled with Lazarus / FreePascal under Linux tested on a Raspberry Pi. This error message appears even though the libtgputty.so library is included in the same directory.

Regards, Olaf

> pi@raspberrypi:~ $ /home/pi/SFTP/FPCSimpleDemos/fpcsftpclasstest
TGPuttyLib not available: /home/pi/SFTP/FPCSimpleDemos/libtgputty.so: cannot open shared object file: No such file or directory
Testing is done ... press ENTER.

>pi@raspberrypi:~ $

**Comment by superflexible** [comment]
Hi,
do you have the correct libtgputty.so for ARM, either 32 bit or 64 bit (aarch64)?

Maybe it helps putting the library in /usr/lib or similar.

**Comment by Oli1L** [comment]
Hi,
the library comes from the folder: /Linux (Compiled Libs)/arm, that comes with the package.
I have Raspbian Bullseye 32 bit installed.
Putting the library in /usr/lib made no difference.

Thanks anyway for your help.

Greetings, Olaf.

**Comment by superflexible** [comment]
Please post the results of
file libtgputty.so
and
ldd libtgputty.so

**Comment by superflexible** [comment]
and also
uname -a

**Comment by Oli1L** [comment]
Hi,

the results is:

> pi@raspberrypi:~ $ sudo find / -name libtgputty.so
> /home/pi/SFTP/libtgputty.so
> /home/pi/SFTP/FPCSimpleDemos/lib/arm-linux/libtgputty.so
> /home/pi/SFTP/FPCSimpleDemos/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/i386/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/x86_64/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/arm/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/ppc64 (ABI V2)/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/ppc/libtgputty.so
> /home/pi/SFTP/Linux (Compiled Libs)/ppc64le/libtgputty.so
> /home/pi/SFTP/FreeBSD (Compiled Libs)/amd64/libtgputty.so
> /usr/local/lib/libtgputty.so
> /usr/lib/libtgputty.so
> find: ‘/run/user/1000/gvfs’: Keine Berechtigung
> pi@raspberrypi:~ $ 
> pi@raspberrypi:~ $ 
> pi@raspberrypi:~ $ 
> pi@raspberrypi:~ $ file libtgputty.so
> libtgputty.so: cannot open `libtgputty.so' (No such file or directory)
> pi@raspberrypi:~ $ ldd libtgputty.so
> ldd: ./libtgputty.so: Datei oder Verzeichnis nicht gefunden
> pi@raspberrypi:~ $ uname -a
> Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
> pi@raspberrypi:~ $ 



Is it possible that the library is not registered on the Raspberry?

**Comment by superflexible** [comment]
You have to cd into the folder with your compiled demo first.

You have many copies of libtgputty.so, and some of them do not match your architecture for sure.

Also do
file /usr/lib/libtgputty.so
ldd /usr/lib/libtgputty.so
etc.

**Comment by Oli1L** [comment]
Hello,

thank you, after LDConfig the output looks like this:

> pi@raspberrypi:~ $ file /usr/lib/libtgputty.so
> /usr/lib/libtgputty.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
> pi@raspberrypi:~ $ file /usr/local/lib/libtgputty.so
> /usr/local/lib/libtgputty.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
> pi@raspberrypi:~ $ ldd /usr/lib/libtgputty.so
> 	das Programm ist nicht dynamisch gelinkt
> pi@raspberrypi:~ $ ldd /usr/local/lib/libtgputty.so
> 	das Programm ist nicht dynamisch gelinkt
> pi@raspberrypi:~ $ 
> pi@raspberrypi:~ $ 
> pi@raspberrypi:~ $ /home/pi/SFTP/FPCSimpleDemos/fpcsftpclasstest
> TGPuttyLib not available: /home/pi/SFTP/FPCSimpleDemos/libtgputty.so: cannot open shared object file: No such file or directory
> Testing is done ... press ENTER.
> 
> pi@raspberrypi:~ $ 

the installed version is the same everywhere (arm 32 bit).
However, calling FCSSFTPClassTest does not work.

Can it be that the library is not dynamically linked (ldd)?

Greetings!

**Comment by superflexible** [comment]
can you enter one more command?

file /home/pi/SFTP/FPCSimpleDemos/libtgputty.so

**Comment by Oli1L** [comment]
This is the output.
The version is the same everywhere.


> pi@raspberrypi:~ $ file /home/pi/SFTP/FPCSimpleDemos/libtgputty.so
> /home/pi/SFTP/FPCSimpleDemos/libtgputty.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
> pi@raspberrypi:~ $ 
>

**Comment by superflexible** [comment]
ok I will test this on a Raspberry myself later today

**Comment by Oli1L** [comment]
Great. I'm starting to think it's the raspberry os. I have now tried every version of the package. Without success. I thank you for your help.

Greetings from germany.

**Comment by superflexible** [comment]
Hi,
it looks like I can confirm the problem. Maybe the 32-bit library isn't compatible with Raspberry PI OS. I will look into it, but if you could just upgrade to a 64-bit OS, such problems will go away. The 64-bit ARM architecture (Aarch64) is much better standardized and it will surely work fine.

**Comment by Oli1L** [comment]
Thank you very much for your quick reply.
I'll test the 64 bit version after I've switched the OS to BullsEye 64 bit.

bye. :-)

**Comment by Oli1L** [comment]
Hello, on Raspberry Pi OS Bullseye 64 bit the library libtgputty.so works fine. The SFTP units for FreePascal / Lazarus can now be integrated without errors. Thank you for your help.

Best regards, Olaf

> pi@raspberrypi:~ $ /home/pi/tmp/fpcsftpclasstest
> Enter Hostname or IP of SFTP Server:
