### ISSUE TITLE
Enable delayed loading of tgputtylib.dll

### ISSUE THREAD

**Issue by rosch100** [superflexible/TGPuttyLib#3]
I suggest to add the "delayed" decorator in the external function declarations of tgputtylib.pas so that the dll is not statically linked to the application.
This enables applications to still run when the dll is not present. It is very useful in e.g. cases, when sftp is only used in rare occasions or optional (as is the case in my program).

**Comment by superflexible** [comment]
Great idea, I will add this soon.

**Comment by superflexible** [comment]
This change has been applied now.
