### ISSUE TITLE
Error "User aborted at host key verification" during connection

### ISSUE THREAD

**Issue by giuseppe-garzotto** [superflexible/TGPuttyLib#32]
Hello,

I'm trying to connect to an SFTP server where I've already do a connection with WinSCP, so I already have the SHA key stored locally.

Using your VCL SFTP Client Demo, all works properly.

Doing the same things in my code, I get an error related host key 

**This is the log returned by VCL SFTP Client demo:**

Library version: tgputtylib build 19 based on PuTTY Release 0.76
Connecting with 195.120.142.110, port 22, as user VER-APLS.
psftp_connect connecting with 195.120.142.110, port 22, as user VER-APLS.
Looking up host "195.120.142.110" for SSH connection
Connecting to 195.120.142.110 port 22
We claim version: SSH-2.0-tgputtylib_Release_0.76
Connected to 195.120.142.110
Remote version: SSH-2.0-OpenSSH_7.4
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve Curve25519 and hash SHA-256 (SHA-NI accelerated)
Server also has ecdsa-sha2-nistp256/rsa-sha2-512/rsa-sha2-256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 255 SHA256:0bgtkSace9Ec2iE1dKT77JueZuS/4pX067GyxWiHzkc
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (SHA-NI accelerated) outbound MAC algorithm
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (SHA-NI accelerated) inbound MAC algorithm
Using username "--------".
Using SSPI from SECUR32.DLL
Trying gssapi-with-mic...
Attempting GSSAPI authentication
GSSAPI authentication request refused
Sent password
Access granted
Opening main session channel
Opened main channel
Started a shell/command
Connected to 195.120.142.110
psftp_connect result is 0
Remote working directory is /------------
do_sftp_init result is 0
tgsftp_connect final result is 0
Canonified /------------ to /------------
Canonified . to /------------

**This is the log returned by my code:**

Connecting with 195.120.142.110, port 22, as user VER-APLS.
psftp_connect connecting with 195.120.142.110, port 22, as user VER-APLS.
Looking up host "195.120.142.110" for SSH connection
Connecting to 195.120.142.110 port 22
We claim version: SSH-2.0-tgputtylib_Release_0.76
Connected to 195.120.142.110
Remote version: SSH-2.0-OpenSSH_7.4
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve Curve25519 and hash SHA-256 (SHA-NI accelerated)
Server also has ecdsa-sha2-nistp256/rsa-sha2-512/rsa-sha2-256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 255 SHA256:0bgtkSace9Ec2iE1dKT77JueZuS/4pX067GyxWiHzkc
User aborted at host key verification
psftp_connect result is 1
tgsftp_connect final result is 1

The code is straightforward: create the class, assign property HostName, Port, UserName and Password, and call Connect.
I can't figure out what is missing.

Thanks

P.S. in VCL SFTP Client Demo there is a typo in registry path where credential are saved: 

      if OpenKey('SOFWARE\tgputty',true) then begin

SOFWARE and not SOFTWARE

**Comment by superflexible** [comment]
Hello,
the SSH host key is verified using a callback function / event handler.

You need to implement this event handler and make sure it accepts the SSH server fingerprint.

So, somewhere you need code similar to this:

function TYourClass.VerifyHostKeyCallback(const host:PAnsiChar;
                                   const port:Integer;
                                   const fingerprint:PAnsiChar;
                                   const verificationstatus:Integer;
                                   var storehostkey:Boolean):Boolean;
begin
   Result:=true; // but you should check the fingerprint first
   end;


PSFTPClient.OnVerifyHostKey:=VerifyHostKeyCallback;

The details may vary depending on which TGPuttyLib class you are using (TTGPuttySFTP or TTGPuttySFTPClient).

**Comment by giuseppe-garzotto** [comment]
OK, I defined the callback routine and assigned it to my wrapper class, but I didn't assign to class property.

Thanks

**Comment by superflexible** [comment]
Great, thanks.
