### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by marcianobandeira** [superflexible/TGPuttyLib#33]
Is it possible to create an SSH tunnel, that is, pass parameters when connecting to the server?
For example, via the command line I can map a local port pointing to the server:

ssh -L 5454:localhost:5454 -L 6379:localhost:6379 user@host

in this example, I am mapping my local ports, to ports on the linux server
Thanks

**Comment by superflexible** [comment]
Hello,
TGPuttyLib is a DLL conversion of the psftp program, not ssh.

It currently supports the SFTP protocol only. You can specify Proxies however.

The most important command line parameters of psftp are available for developers.

**Comment by superflexible** [comment]
SSH features have been added now!
