### ISSUE TITLE
Arquivos Textos com mais de 64kb não fazem UPLOAD.

### ISSUE THREAD

**Issue by AndreBrandao1972** [superflexible/TGPuttyLib#35]
Olá,

Estou com problema de envio de arquivos usando o comando PSFTP.UploadStream, ele somente aceita no UPLOAD arquivos textos com mesmo de 64kb, como podemos solucionar esta situação ?

  UploadStream := TFileStream.Create(APath, fmOpenRead);
  PSFTP.UploadStream(System.UTF8Encode(lArquivo), UploadStream, False);

**Comment by superflexible** [comment]
It is an unusual problem. Which error do you get?

Can you try one of the precompiled demos which are part of the Release zip?

**Comment by AndreBrandao1972** [comment]
Estamos enviando um arquivo acima de 64kb para um servidor SFTP, porem esse servidor quando recebe o arquivo na pasta, move o arquivo para outra pasta, então antes do termino do envio do arquivo atraves do comando PSFTP.UploadStream(System.UTF8Encode(lArquivo), UploadStream, TRUE), o processamento de envio da erro, porque o arquivo nao esta mais na pasta. Pergunto, tem como bloquear o arquivo em modo exclusivo, enquanto ele ainda esta sendo enviado para o SFTP?

**Comment by superflexible** [comment]
If the destination system cannot easily be made to ignore .$$$ files, you should upload into a different folder, then use the rename command to move the file into the target folder.

**Comment by AndreBrandao1972** [comment]
Esse é o ERRO : Remote side sent disconnect message type 11 (by application): "User Disconnected" - 26/01/2024 10:10:26
FATAL ERROR: Remote side sent disconnect messagetype 11 (by application):"User Disconnected" - 26/01/2024 10:10:26
 - 26/01/2024 10:10:26
error while writing: xfer_upload_gotpkt: no pktin, possibly not connected - 26/01/2024 10:10:26

**Comment by superflexible** [comment]
No. You must use a temporary filename or upload into a different folder.

Most likely, the people that manage the server have to fix something on their end.
