### ISSUE TITLE
Carregar Configurações Salvas

### ISSUE THREAD

**Issue by AndreBrandao1972** [superflexible/TGPuttyLib#36]
Como carregar as configurações de conexão do putty salvas  em 
Computador\HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\Default%20Settings antes do Connect

**Comment by superflexible** [comment]
Hello,
I don't know if it's possible. The idea of the DLL is to be completely independent and to set all parameters in your code.

**Comment by AndreBrandao1972** [comment]
Como é possível configurar a DLL com essas opções da imagem ?
![IMG-20240201-WA0120(1)](https://github.com/superflexible/TGPuttyLib/assets/157631975/46183848-5d35-4ac3-8a6d-2a0cd29a1dc6)

**Comment by superflexible** [comment]
Interesting question, I will check and let you know.

**Comment by AndreBrandao1972** [comment]
Bom dia, 
Alguma novidade ?

**Comment by superflexible** [comment]
Hello,
all the configuration item are defined in tgputtylib.pas.

I am assuming you have an SFTP instance of TTGPuttySFTP named PuSFTP:
var PuSFTP:TTGPuttySFTP;

Then you can do:
PuSFTP.SetBooleanConfigValue(cPuttyConf_tcp_keepalives,true); // default false
PuSFTP.SetBooleanConfigValue(cPuttyConf_tcp_nodelay,true); // default true

For the interval of 30 seconds, I am not totally sure, is it the "ping interval"?
In that case:
PuSFTP.SetIntegerConfigValue(cPuttyConf_ping_interval,30);

**Comment by AndreBrandao1972** [comment]
Obrigado pelo retorno, porem todas as vezes que tento enviar um arquivo texto acima de 60kb o comando PSFTP.UploadStream(ARemoteFilename, UploadStream, False) Trava e copia o arquivo pro SFTP com 0kb. Utilizando o WINSCP o arquivo com 100kb é enviado normalmente. Tem alguma solução para enviar o arquivo por partes ?
Sempre apresenta o erro abaixo:
Remote side sent disconnect message type 11 (by application): "User Disconnected" - 05/02/2024 20:42:13
FATAL ERROR: Remote side sent disconnect messagetype 11 (by application):"User Disconnected" - 05/02/2024 20:42:13
 - 05/02/2024 20:42:13
error while writing: xfer_upload_gotpkt: no pktin, possibly not connected - 05/02/2024 20:42:13

**Comment by superflexible** [comment]
Maybe the server cannot tolerate the bigger buffer size in TGPuttyLib.

Is there any way you could provide a test SFTP login? If yes, please send it to support@syncovery.com.

**Comment by AndreBrandao1972** [comment]
E como contornar essa questão do tamanho maior do buffer ?

**Comment by superflexible** [comment]
I can send you some sample code tomorrow.

**Comment by AndreBrandao1972** [comment]
Fico grato.

**Comment by AndreBrandao1972** [comment]
Ola, no aguardo do codigo...Obrigado!

**Comment by superflexible** [comment]
Hello,
I am working on it now. I have to prepare it and test it.

**Comment by AndreBrandao1972** [comment]
Alguma evolução?

**Comment by superflexible** [comment]
Hello,
you can now set a small upload buffer size with this command in your Delphi/Pascal code:
tgputty_conf_set_int(cSetUploadBufSizeConfNum,4096,nil);

Be sure to call this before doing any uploads.

You need a updated version of tgputtylib.pas:
https://github.com/superflexible/TGPuttyLib/blob/master/tgputtylib.pas

And the DLL itself also has to be updated to build 27:
https://github.com/superflexible/TGPuttyLib/tree/master/Win64/Debug
or
https://github.com/superflexible/TGPuttyLib/tree/master/Win32/Debug

I hope this fixes the problem.

**Comment by AndreBrandao1972** [comment]
Quando executa o programa esta com a mensagem abaixo, depois de atualizada DLL e .PAS

![image](https://github.com/superflexible/TGPuttyLib/assets/157631975/7440fd41-c206-40e7-bab6-6b4eb2d95eab)

**Comment by AndreBrandao1972** [comment]
Atualizei toda a pasta e funcionouuu.... Obrigadooo
