### ISSUE TITLE
Consider moving the the EXE files to a branch?

### ISSUE THREAD

**Issue by edwinyzh** [superflexible/TGPuttyLib#6]
From time to time, updating local repository fails no matter it's TortoiseSVN or GitExtension, using direction connection or going through Socks5 proxy. I guess it maybe because there a quite amount of the big EXE files in the repo.

Would you consider separate those DEMO EXEs out of the source repository? 

Thanks for your consideration.

**Comment by superflexible** [comment]
Hello,
yes I think it will be sufficient to include the EXEs in the Releases.

Do you think the compiled DLL can be kept in the repository? I want to make it really easy for users to get it. Nobody should think they need to compile it manually.

**Comment by superflexible** [comment]
I have implemented this change now.

**Comment by edwinyzh** [comment]
@superflexible  Thank you! I think the compiled DLLs should be included in the repository for the easy life of the users, because the size is not a transferring burden for the git/svn client tools.
