### ISSUE TITLE
Ask I ask the motivation of this project?

### ISSUE THREAD

**Issue by edwinyzh** [superflexible/TGPuttyLib#7]
This is definitely a useful project! Just out of curiosity - why don't use libssh directly? From the homepage I read  that the advantage of TGPuttyLib is faster transfer speed?

I've no experience with libssh nor TGPuttyLib yet, but will need to implement sFTP transfer function in the near future, so will be happy to hear about how do you think. Because I guess using libssh needs less work if libssh satisfied you at the very beginning.

And happy holidays!

**Comment by superflexible** [comment]
Hello,
yes, the transfer rates are much higher than with libssh.


-----

Please excuse the shortness of this mail which was sent from my mobile phone. If necessary, I will send more information later.

Cheers,
Tobias Giesen

**Comment by superflexible** [comment]
To give you some more background, my customers have always asking to see the same performance as FileZilla. FileZilla uses a modified psftp.exe from PuTTY. My testing has shown that the only way to get the same transfer speed as FileZilla is to use PuTTY, so I created this DLL. I think that a DLL is more useful than using an external exe file for transfers.

**Comment by edwinyzh** [comment]
> To give you some more background, my customers have always been requesting to see the same performance as FileZilla. FileZilla uses a modified psftp.exe from PuTTY. My testing has shown that the only way to get the same transfer speed as FileZilla is to use PuTTY, so I created this DLL. I think that a DLL is more useful than using an external exe file for transfers.

That sounds great!
