### ISSUE TITLE
Compiler error under Xe4, but I'll fix it some time later when I started using it if you don't :)

### ISSUE THREAD

**Issue by edwinyzh** [superflexible/TGPuttyLib#8]
Get this error when compiling it with XE$ for the first time:
`[dcc32 Error] tgputtysftp.pas(494): E2034 Too many actual parameters`
at:
`  attrs.mtime:=DateTimeToUnix(ATimestamp,isUTC);`

I guess it's just a very small issue and I'll fix it when I started using it some time later if you don't , but just report it here first :)

Happy holidays :)

**Comment by superflexible** [comment]
For the moment you can just remove the isUTC parameter but I will provide a proper fix. Or you can submit it via Pull Request or just paste it here.

**Comment by edwinyzh** [comment]
By the time I start evaluating TGPuttyLib for my project if there is not a fix yet, I'll do the fix  and submit a PR.

**Comment by superflexible** [comment]
Hello,
I have pushed some changes to fix it, can you test?

**Comment by edwinyzh** [comment]
Hey, it compiles now and DelphiVCLDemo works as expected! Thank you man!

**Comment by superflexible** [comment]
Thanks for testing!
