### ISSUE TITLE
Connect to SFTP server with private key

### ISSUE THREAD

**Issue by aleixmascaro** [superflexible/TGPuttyLib#9]
Hi, there is any way to connect to a SFTP  server with a private key(without using a password)?.
I only  have a ppk file and i don't have the password.

**Comment by superflexible** [comment]
Hello,
yes, just set the UserName and KeyFile properties. You may also need the KeyPassword.

The Keyfile property is not available at design time, you need to set it in your code.

**Comment by aleixmascaro** [comment]
Ok, thanks!
Can you give me a little example of that to confirm if i understand?
KeyFile: the directory of the ppk file
But i don't know what is the KeyPassword. Is another kind of file or is a string?

**Comment by superflexible** [comment]
Hello,
if you don't know the password, you probably don't have one for the key.

Then it is an empty string.

**Comment by aleixmascaro** [comment]
Okei,  it help my a lot!!
Thank you very much!!!!
